### PR TITLE
corrected composer-api version requirement

### PR DESCRIPTION
**Pull request by Basster**
Broke after the composer 1.1 release.

> phpdocumentor/unified-asset-installer 1.1.2 requires composer-plugin-api 1.0.0 -> no matching package found.

### CODE REVIEW

**Comment by Basster** [comment]
See comment of @Seldaek here: https://github.com/composer/composer/issues/5252#issuecomment-215565451

**Comment by kingjerod** [comment]
Will this get merged soon? Preventing some devs from getting environments up and running and also causing a lot of failing builds.

**Comment by DannyvdSluijs** [comment]
@mvriel can we maybe merge this. We are experiencing the same as above.

**Comment by dannyvw** [comment]
@mvriel can we merge this?

**Comment by bijsterdee** [comment]
+1 merge this please!

**Comment by mvriel** [comment]
Ok, for some odd reason I never saw this PR. My sincere apologies for leaving it hanging!

**Pull request merged**
